### ISSUE TITLE
Annotations not working with Mirador

### ISSUE THREAD

**Issue by eltiffster** [UVicLibrary/CustomSpotlightInstance#48]

**Comment by eltiffster** [comment]
Note to double check permissions for annotations

**Comment by eltiffster** [comment]
Permissions weren't working and originally tried to change it in `views/catalog/_openseadragon` partial but the iframe loads at a different time. Moving the changes to the `_manifest_fullscreen` partial fixed the problem.

```css
<!-- Disable annotation creation for non-admins (Mirador annotations config doesn't seem to work in mirador_rails) -->
<% unless can? :manage, @page %>
  <style>
    .annotation-display.annotation-tooltip .button-container {
      display: none !important;
    }
    .mirador-osd-annotation-controls a:not(:first-child) *, .mirador-container .hud-control.mirador-line-type {
      display: none !important;
    }
  </style>
<% end %>
```
