### ISSUE TITLE
Some annotation buttons for Mirador are too small

### ISSUE THREAD

**Issue by eltiffster** [UVicLibrary/CustomSpotlightInstance#54]

**Comment by eltiffster** [comment]
In the gem, there is a stylesheet called mirador-combined.css.

Around line 2468:
```css
.mirador-container .mirador-osd-color-picker .sp-replacer {
  border-color: #ccc;
  /* height: 11px; */
  height: 21px;
  border-radius: 3px;
  cursor: default;
}

.mirador-container .hud-control.mirador-line-type {
  /* height: 11px; */
  height: 21px;
  border-radius: 3px;
  margin: 2px 11px 0 0;
  padding: 4px;
  /* width: 57px; */
  border: 1px solid #ccc;
  background: #eee none repeat scroll 0 0;
  text-shadow: none;
  color: #333;
}
```

**Comment by eltiffster** [comment]
Also fixed where showing annotations are too small. In `mirador-combined.css` in Mirador gem:
```css
qtip-content {
min-height: 250px;
}
```
